"""initial schema - all 19 tables

Revision ID: 94682e9efb66
Revises: 
Create Date: 2026-08-29 08:07:52.052635

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '94682e9efb66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('item_type', sa.Enum('exp', 'stat_points', 'cosmetic', 'temporary_bonus', 'special', name='itemtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lootboxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.Enum('weight', 'body_fat', 'resting_hr', 'sleep', 'steps', 'distance', 'active_energy', 'vo2max', name='metrictype'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('base_unit', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_definitions_metric_type'), 'metric_definitions', ['metric_type'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('endurance', sa.Integer(), nullable=False),
    sa.Column('core', sa.Integer(), nullable=False),
    sa.Column('recovery', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('condition', sqlite.JSON(), nullable=True),
    sa.Column('reward_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reward_id'], ['items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_code'), 'achievements', ['code'], unique=True)
    op.create_table('bosses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('target_type', sa.Enum('weight', 'exercise', 'distance', 'streak', 'quests', name='bosstargettype'), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('is_defeated', sa.Boolean(), nullable=False),
    sa.Column('defeated_at', sa.DateTime(), nullable=True),
    sa.Column('reward_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reward_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bosses_user_id'), 'bosses', ['user_id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.Enum('strength', 'core', 'cardio', 'recovery', name='exercisecategory'), nullable=False),
    sa.Column('measurement_type', sa.Enum('reps', 'seconds', 'distance', 'weight', 'duration', name='measurementtype'), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=True)
    op.create_table('lootbox_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lootbox_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lootbox_id'], ['lootboxes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lootbox_rewards_item_id'), 'lootbox_rewards', ['item_id'], unique=False)
    op.create_index(op.f('ix_lootbox_rewards_lootbox_id'), 'lootbox_rewards', ['lootbox_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('goal_notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('raw_health_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'parsed', 'error', 'deleted', name='importstatus'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'file_hash', name='uq_imports_user_hash')
    )
    op.create_index(op.f('ix_raw_health_imports_file_hash'), 'raw_health_imports', ['file_hash'], unique=False)
    op.create_index(op.f('ix_raw_health_imports_user_id'), 'raw_health_imports', ['user_id'], unique=False)
    op.create_table('readiness_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('training_modifier', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_readiness_user_date')
    )
    op.create_index(op.f('ix_readiness_scores_user_id'), 'readiness_scores', ['user_id'], unique=False)
    op.create_table('user_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', name='uq_inventory_user_item')
    )
    op.create_index(op.f('ix_user_inventory_item_id'), 'user_inventory', ['item_id'], unique=False)
    op.create_index(op.f('ix_user_inventory_user_id'), 'user_inventory', ['user_id'], unique=False)
    op.create_table('calibration_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_records_exercise_id'), 'calibration_records', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_calibration_records_user_id'), 'calibration_records', ['user_id'], unique=False)
    op.create_table('health_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metric_type', sa.Enum('weight', 'body_fat', 'resting_hr', 'sleep', 'steps', 'distance', 'active_energy', 'vo2max', name='metrictype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('raw_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['raw_health_imports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_metrics_import_id'), 'health_metrics', ['import_id'], unique=False)
    op.create_index('ix_health_metrics_metric', 'health_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_health_metrics_user_id'), 'health_metrics', ['user_id'], unique=False)
    op.create_index('ix_health_metrics_user_metric_ts', 'health_metrics', ['user_id', 'metric_type', 'timestamp'], unique=False)
    op.create_index('ix_health_metrics_user_ts', 'health_metrics', ['user_id', 'timestamp'], unique=False)
    op.create_table('quest_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('category', sa.Enum('strength', 'core', 'cardio', 'recovery', name='exercisecategory'), nullable=False),
    sa.Column('base_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('base_exp', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Enum('info', 'warning', 'error', name='syncloglevel'), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['raw_health_imports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_import_id'), 'sync_logs', ['import_id'], unique=False)
    op.create_index(op.f('ix_sync_logs_user_id'), 'sync_logs', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('daily_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('category', sa.Enum('strength', 'core', 'cardio', 'recovery', name='exercisecategory'), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('exp_reward', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'auto_completed', 'skipped', name='queststatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['quest_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', 'template_id', name='uq_daily_user_date_template')
    )
    op.create_index('ix_daily_quests_user_date', 'daily_quests', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_daily_quests_user_id'), 'daily_quests', ['user_id'], unique=False)
    op.create_table('quest_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('planned_value', sa.Float(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=False),
    sa.Column('exp_earned', sa.Integer(), nullable=False),
    sa.Column('modifier', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'auto', name='completionsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['daily_quests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quest_completions_user_date', 'quest_completions', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_quest_completions_user_id'), 'quest_completions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quest_completions_user_id'), table_name='quest_completions')
    op.drop_index('ix_quest_completions_user_date', table_name='quest_completions')
    op.drop_table('quest_completions')
    op.drop_index(op.f('ix_daily_quests_user_id'), table_name='daily_quests')
    op.drop_index('ix_daily_quests_user_date', table_name='daily_quests')
    op.drop_table('daily_quests')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_sync_logs_user_id'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_import_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_table('quest_templates')
    op.drop_index('ix_health_metrics_user_ts', table_name='health_metrics')
    op.drop_index('ix_health_metrics_user_metric_ts', table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_user_id'), table_name='health_metrics')
    op.drop_index('ix_health_metrics_metric', table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_import_id'), table_name='health_metrics')
    op.drop_table('health_metrics')
    op.drop_index(op.f('ix_calibration_records_user_id'), table_name='calibration_records')
    op.drop_index(op.f('ix_calibration_records_exercise_id'), table_name='calibration_records')
    op.drop_table('calibration_records')
    op.drop_index(op.f('ix_user_inventory_user_id'), table_name='user_inventory')
    op.drop_index(op.f('ix_user_inventory_item_id'), table_name='user_inventory')
    op.drop_table('user_inventory')
    op.drop_index(op.f('ix_readiness_scores_user_id'), table_name='readiness_scores')
    op.drop_table('readiness_scores')
    op.drop_index(op.f('ix_raw_health_imports_user_id'), table_name='raw_health_imports')
    op.drop_index(op.f('ix_raw_health_imports_file_hash'), table_name='raw_health_imports')
    op.drop_table('raw_health_imports')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_lootbox_rewards_lootbox_id'), table_name='lootbox_rewards')
    op.drop_index(op.f('ix_lootbox_rewards_item_id'), table_name='lootbox_rewards')
    op.drop_table('lootbox_rewards')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_bosses_user_id'), table_name='bosses')
    op.drop_table('bosses')
    op.drop_index(op.f('ix_achievements_code'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_metric_definitions_metric_type'), table_name='metric_definitions')
    op.drop_table('metric_definitions')
    op.drop_table('lootboxes')
    op.drop_table('items')
    # ### end Alembic commands ###
